#!/usr/bin/env python

import binascii
import pyaudio
import os
import subprocess
import sys
import threading

# Constants
RATE = 44100
CHUNK = 1024

# Redirect c-level stderr to avoid annoying PortAudio debugging info
sys.stderr = os.fdopen(os.dup(2), 'w')
os.dup2(os.open('/dev/null', 0), 2)
 
audio = pyaudio.PyAudio()

stream = audio.open( format=pyaudio.paInt16
                   , channels=1
                   , rate=RATE
                   , input=True
                   , frames_per_buffer=CHUNK
                   )

done = threading.Event()

def set_on_input(e):
    raw_input()
    done.set()

# Thread waits for line of keyboard input (<enter>)
threading.Thread(target=set_on_input, args=(done,)).start()

# Git will take audio data as commit message from stdin
p = subprocess.Popen(['git', 'commit', '--cleanup=verbatim', '-F', '-'], stdin=subprocess.PIPE)

sys.stderr.write('Press <enter> to stop recording\n')

p.stdin.write('(audio)\n\n')
while not done.is_set():
    p.stdin.write(binascii.hexlify(stream.read(CHUNK)))

stream.stop_stream()
stream.close()
audio.terminate()
