#!/usr/bin/env python

import binascii
import pyaudio
import subprocess
import sys
import threading

RATE = 44100
CHUNK = 1024
 
audio = pyaudio.PyAudio()

stream = audio.open( format=pyaudio.paInt16
                   , channels=1
                   , rate=RATE
                   , input=True
                   , frames_per_buffer=CHUNK
                   )

done = threading.Event()

def set_on_input(e):
    raw_input()
    done.set()

threading.Thread(target=set_on_input, args=(done,)).start()

p = subprocess.Popen(['git', 'commit', '--cleanup=verbatim', '-F', '-'], stdin=subprocess.PIPE)

sys.stderr.write('Press <enter> to stop recording\n')

p.stdin.write('(audio)\n\n')
while not done.is_set():
    p.stdin.write(binascii.hexlify(stream.read(CHUNK)))

stream.stop_stream()
stream.close()
audio.terminate()
