#!/usr/bin/env python

import binascii
import datetime
import os
import pyaudio
import pygit2
import sys

sys.stderr = None

RATE = 44100
CHUNK = 1024

audio = pyaudio.PyAudio()

stream = audio.open( format=pyaudio.paInt16
                   , channels=1
                   , rate=RATE
                   , output=True
                   , frames_per_buffer=CHUNK
                   )

repo = pygit2.Repository(pygit2.discover_repository(os.getcwd()))

PREFIX = '(audio)'

for commit in repo.walk(repo.head.target, pygit2.GIT_SORT_TOPOLOGICAL):
    print('commit {}'.format(commit.oid))
    print('Author:\t{} <{}>'.format(commit.author.name, commit.author.email))
    print('Date:\t{}'.format(datetime.datetime.fromtimestamp(commit.commit_time)))
    print('')
    if commit.message.startswith(PREFIX):
        sys.stdout.write('\t{}\n\n'.format(PREFIX))
        stream.write(binascii.unhexlify(commit.message[len(PREFIX)+2:]))
    else:
        sys.stdout.write('\t')
        sys.stdout.write(commit.message)

stream.stop_stream()
stream.close()
audio.terminate()
